"""
Support for Constants.
"""
from datetime import timedelta

import aiohttp

from homeassistant.const import UnitOfDataRate, UnitOfInformation

from .enums import (
    DeviceTypes,
    DynamicInterfaceTypes,
    EntityValidation,
    InterfaceTypes,
    UnitOfEdgeOS,
)

ENTITY_CONFIG_ENTRY_ID = "entry_id"

HA_NAME = "homeassistant"

DOMAIN = "edgeos"
DEFAULT_NAME = "EdgeOS"
MANUFACTURER = "Ubiquiti"

STORAGE_DATA_KEY = "key"

SIGNAL_INTERFACE_ADDED = f"{DOMAIN}_INTERFACE_ADDED_SIGNAL"
SIGNAL_DEVICE_ADDED = f"{DOMAIN}_DEVICE_ADDED_SIGNAL"
SIGNAL_SYSTEM_ADDED = f"{DOMAIN}_SYSTEM_ADDED_SIGNAL"
SIGNAL_DATA_CHANGED = f"{DOMAIN}_DATA_CHANGED_SIGNAL"

SIGNAL_WS_STATUS = f"{DOMAIN}_WS_STATUS_SIGNAL"
SIGNAL_API_STATUS = f"{DOMAIN}_API_STATUS_SIGNAL"

ADD_COMPONENT_SIGNALS = [
    SIGNAL_INTERFACE_ADDED,
    SIGNAL_DEVICE_ADDED,
    SIGNAL_SYSTEM_ADDED,
]

MAXIMUM_RECONNECT = 3
CONFIGURATION_FILE = f"{DOMAIN}.config.json"

INVALID_TOKEN_SECTION = "https://github.com/elad-bar/ha-edgeos#invalid-token"

API_URL_TEMPLATE = "https://{}"
WEBSOCKET_URL_TEMPLATE = "wss://{}/ws/stats"

COOKIE_PHPSESSID = "PHPSESSID"
COOKIE_BEAKER_SESSION_ID = "beaker.session.id"
COOKIE_CSRF_TOKEN = "X-CSRF-TOKEN"

HEADER_CSRF_TOKEN = "X-Csrf-token"
EMPTY_STRING = ""
CONF_TITLE = "title"

ATTR_ATTRIBUTES = "attributes"
ATTR_ACTIONS = "actions"
ATTR_IS_ON = "is_on"
ATTR_LAST_ACTIVITY = "last activity"
ATTR_HOSTNAME = "hostname"

ACTION_ENTITY_TURN_ON = "turn_on"
ACTION_ENTITY_TURN_OFF = "turn_off"
ACTION_ENTITY_SET_NATIVE_VALUE = "set_native_value"
ACTION_ENTITY_SELECT_OPTION = "select_option"

WS_MAX_MSG_SIZE = 0
DISCONNECT_INTERVAL = 5

WS_RECONNECT_INTERVAL = timedelta(seconds=30)
WS_TIMEOUT = timedelta(minutes=1)

WS_COMPRESSION_DEFLATE = 15

DEFAULT_UPDATE_API_INTERVAL = timedelta(minutes=1)
DEFAULT_UPDATE_ENTITIES_INTERVAL = timedelta(seconds=1)
DEFAULT_CONSIDER_AWAY_INTERVAL = timedelta(minutes=3)
API_RECONNECT_INTERVAL = timedelta(seconds=30)
HEARTBEAT_INTERVAL = timedelta(seconds=25)

STORAGE_DATA_MONITORED_INTERFACES = "monitored-interfaces"
STORAGE_DATA_MONITORED_DEVICES = "monitored-devices"
STORAGE_DATA_LOG_INCOMING_MESSAGES = "log-incoming-messages"
STORAGE_DATA_CONSIDER_AWAY_INTERVAL = "consider-away-interval"
STORAGE_DATA_UPDATE_ENTITIES_INTERVAL = "update-entities-interval"
STORAGE_DATA_UPDATE_API_INTERVAL = "update-api-interval"
STORAGE_DATA_UNIT = "unit"

API_DATA_LAST_UPDATE = "lastUpdate"

API_DATA_PRODUCT = "product"
API_DATA_SYSTEM = "system"
API_DATA_INTERFACES = "interfaces"
API_DATA_SESSION_ID = "session-id"
API_DATA_COOKIES = "cookies"

API_DATA_SAVE = "SAVE"

API_GET = "get"
API_SET = "set"
API_DELETE = "delete"
API_DATA = "data"

API_URL_PARAMETER_BASE_URL = "base_url"
API_URL_PARAMETER_TIMESTAMP = "timestamp"
API_URL_PARAMETER_ACTION = "action"
API_URL_PARAMETER_SUBSET = "subset"

API_URL_HEARTBEAT = "{base_url}?_={timestamp}"
API_URL_DATA = "{base_url}/api/edge/{action}.json"
API_URL_DATA_SUBSET = f"{API_URL_DATA}?data={{subset}}"

TRUE_STR = "true"
FALSE_STR = "false"

INTERFACES_STATS = "stats"

# CHANGE TO API DATA
API_DATA_DHCP_STATS = "dhcp_stats"
API_DATA_SYS_INFO = "sys_info"
API_DATA_DHCP_LEASES = "dhcp-leases"

DATA_SYSTEM_SYSTEM = "system"
DATA_SYSTEM_SERVICE = "service"
DATA_SYSTEM_SERVICE_DHCP_SERVER = "dhcp-server"

DHCP_SERVER_LEASES = "dhcp-server-leases"
DHCP_SERVER_STATS = "dhcp-server-stats"
DHCP_SERVER_LEASED = "leased"
DHCP_SERVER_LEASES_CLIENT_HOSTNAME = "client-hostname"
DHCP_SERVER_SHARED_NETWORK_NAME = "shared-network-name"
DHCP_SERVER_SUBNET = "subnet"
DHCP_SERVER_STATIC_MAPPING = "static-mapping"
DHCP_SERVER_IP_ADDRESS = "ip-address"
DHCP_SERVER_MAC_ADDRESS = "mac-address"

WS_INTERFACES_KEY = "interfaces"
WS_SYSTEM_STATS_KEY = "system-stats"
WS_EXPORT_KEY = "export"
WS_DISCOVER_KEY = "discover"

WS_RECEIVED_MESSAGES = "received-messages"
WS_IGNORED_MESSAGES = "ignored-messages"

UPDATE_DATE_ENDPOINTS = [API_DATA_SYS_INFO, API_DATA_DHCP_STATS, API_DATA_DHCP_LEASES]

DISCOVER_DATA_FW_VERSION = "fwversion"
DISCOVER_DATA_PRODUCT = "product"

SYSTEM_STATS_DATA_UPTIME = "uptime"
SYSTEM_STATS_DATA_CPU = "cpu"
SYSTEM_STATS_DATA_MEM = "mem"

DEVICE_LIST = "devices"
ADDRESS_LIST = "addresses"
ADDRESS_IPV4 = "ipv4"
ADDRESS_HW_ADDR = "hwaddr"

RESPONSE_SUCCESS_KEY = "success"
RESPONSE_ERROR_KEY = "error"
RESPONSE_OUTPUT = "output"
RESPONSE_FAILURE_CODE = "0"

HEARTBEAT_MAX_AGE = 15

WS_TOPIC_NAME = "name"
WS_TOPIC_UNSUBSCRIBE = "UNSUBSCRIBE"
WS_TOPIC_SUBSCRIBE = "SUBSCRIBE"
WS_SESSION_ID = "SESSION_ID"

BEGINS_WITH_SIX_DIGITS = "^([0-9]{1,6})"

STRING_DASH = "-"
STRING_UNDERSCORE = "_"
STRING_COMMA = ","
STRING_COLON = ":"

SYSTEM_DATA_HOSTNAME = "host-name"
SYSTEM_DATA_DOMAIN_NAME = "domain-name"
SYSTEM_DATA_NTP = "ntp"
SYSTEM_DATA_NTP_SERVER = "server"
SYSTEM_DATA_OFFLOAD = "offload"
SYSTEM_DATA_OFFLOAD_HW_NAT = "hwnat"
SYSTEM_DATA_OFFLOAD_IPSEC = "ipsec"
SYSTEM_DATA_TRAFFIC_ANALYSIS = "traffic-analysis"
SYSTEM_DATA_TRAFFIC_ANALYSIS_DPI = "dpi"
SYSTEM_DATA_TRAFFIC_ANALYSIS_EXPORT = "export"
SYSTEM_DATA_TIME_ZONE = "time-zone"
SYSTEM_DATA_LOGIN = "login"
SYSTEM_DATA_LOGIN_USER = "user"
SYSTEM_DATA_LOGIN_USER_LEVEL = "level"

USER_LEVEL_ADMIN = "admin"

SYSTEM_INFO_DATA_FW_LATEST = "fw-latest"
SYSTEM_INFO_DATA_FW_LATEST_STATE = "state"
SYSTEM_INFO_DATA_FW_LATEST_VERSION = "version"
SYSTEM_INFO_DATA_FW_LATEST_URL = "url"

FW_LATEST_STATE_CAN_UPGRADE = "can-upgrade"

SYSTEM_INFO_DATA_SW_VER = "sw_ver"

SYSTEM_DATA_ENABLE = "enable"
SYSTEM_DATA_DISABLE = "disable"

INTERFACE_DATA_NAME = "name"
INTERFACE_DATA_DESCRIPTION = "description"
INTERFACE_DATA_TYPE = "type"
INTERFACE_DATA_DUPLEX = "duplex"
INTERFACE_DATA_SPEED = "speed"
INTERFACE_DATA_BRIDGE_GROUP = "bridge-group"
INTERFACE_DATA_ADDRESS = "address"
INTERFACE_DATA_AGING = "aging"
INTERFACE_DATA_BRIDGED_CONNTRACK = "bridged-conntrack"
INTERFACE_DATA_HELLO_TIME = "hello-time"
INTERFACE_DATA_MAX_AGE = "max-age"
INTERFACE_DATA_PRIORITY = "priority"
INTERFACE_DATA_PROMISCUOUS = "promiscuous"
INTERFACE_DATA_STP = "stp"
INTERFACE_DATA_RECEIVED = "received"
INTERFACE_DATA_SENT = "sent"
INTERFACE_DATA_MULTICAST = "multicast"
INTERFACE_DATA_UP = "up"
INTERFACE_DATA_LINK_UP = "l1up"
INTERFACE_DATA_MAC = "mac"
INTERFACE_DATA_IS_SUPPORTED = "is_supported"

DEVICE_DATA_NAME = "hostname"
DEVICE_DATA_DOMAIN = "domain"
DEVICE_DATA_IP = "ip"
DEVICE_DATA_MAC = "mac"
DEVICE_DATA_RECEIVED = "received"
DEVICE_DATA_SENT = "sent"

TRAFFIC_DATA_DIRECTION = "direction"
TRAFFIC_DATA_RATE = "rate"
TRAFFIC_DATA_TOTAL = "total"
TRAFFIC_DATA_ERRORS = "errors"
TRAFFIC_DATA_PACKETS = "packets"
TRAFFIC_DATA_DROPPED = "dropped"
TRAFFIC_DATA_LAST_ACTIVITY = "last_activity"
TRAFFIC_DATA_LAST_ACTIVITY_IN_SECONDS = "last_activity_in_seconds"

TRAFFIC_STATS_BPS_KEY = "bps"
TRAFFIC_STATS_BYTES = "bytes"

TRAFFIC_DATA_DIRECTION_SENT = "tx"
TRAFFIC_DATA_DIRECTION_RECEIVED = "rx"

TRAFFIC_DATA_DIRECTIONS = [TRAFFIC_DATA_DIRECTION_SENT, TRAFFIC_DATA_DIRECTION_RECEIVED]

TRAFFIC_DATA_INTERFACE_ITEMS = {
    TRAFFIC_STATS_BPS_KEY: TRAFFIC_DATA_RATE,
    TRAFFIC_STATS_BYTES: TRAFFIC_DATA_TOTAL,
    TRAFFIC_DATA_ERRORS: TRAFFIC_DATA_ERRORS,
    TRAFFIC_DATA_PACKETS: TRAFFIC_DATA_PACKETS,
    TRAFFIC_DATA_DROPPED: TRAFFIC_DATA_DROPPED,
}

TRAFFIC_DATA_DEVICE_ITEMS = {
    TRAFFIC_DATA_RATE: TRAFFIC_DATA_RATE,
    TRAFFIC_STATS_BYTES: TRAFFIC_DATA_TOTAL,
}

INTERFACES_MAIN_MAP = [
    INTERFACE_DATA_UP,
    INTERFACE_DATA_LINK_UP,
    INTERFACE_DATA_SPEED,
    INTERFACE_DATA_DUPLEX,
    INTERFACE_DATA_MAC,
]

DISCOVER_DEVICE_ITEMS = [
    DEVICE_DATA_NAME,
    DISCOVER_DATA_PRODUCT,
    SYSTEM_STATS_DATA_UPTIME,
    DISCOVER_DATA_FW_VERSION,
    "system_status",
]

WS_CLOSING_MESSAGE = [
    aiohttp.WSMsgType.CLOSE,
    aiohttp.WSMsgType.CLOSED,
    aiohttp.WSMsgType.CLOSING,
]

SUPPORTED_INTERFACES = [
    InterfaceTypes.ETHERNET,
    InterfaceTypes.BRIDGE,
    InterfaceTypes.SWITCH,
    InterfaceTypes.OPEN_VPN,
    InterfaceTypes.WIREGUARD,
]

SUPPORTED_DYNAMIC_INTERFACES = [
    DynamicInterfaceTypes.PPPOE,
    DynamicInterfaceTypes.VIRTUAL_TUNNEL,
    DynamicInterfaceTypes.BONDING,
]

ATTR_UNIT_INFORMATION = "information"
ATTR_UNIT_RATE = "rate"
ATTR_UNIT_CONVERTOR = "unit_convertor"

UNIT_MAPPING = {
    str(UnitOfInformation.BYTES).lower(): {
        ATTR_UNIT_INFORMATION: UnitOfInformation.BYTES,
        ATTR_UNIT_RATE: UnitOfDataRate.BYTES_PER_SECOND,
        ATTR_UNIT_CONVERTOR: lambda v: v,
    },
    str(UnitOfInformation.KILOBYTES).lower(): {
        ATTR_UNIT_INFORMATION: UnitOfInformation.KILOBYTES,
        ATTR_UNIT_RATE: UnitOfDataRate.KILOBYTES_PER_SECOND,
        ATTR_UNIT_CONVERTOR: lambda v: v / 1024,
    },
    str(UnitOfInformation.MEGABYTES).lower(): {
        ATTR_UNIT_INFORMATION: UnitOfInformation.MEGABYTES,
        ATTR_UNIT_RATE: UnitOfDataRate.MEGABYTES_PER_SECOND,
        ATTR_UNIT_CONVERTOR: lambda v: v / 1024 / 1024,
    },
}

DEFAULT_UNIT = str(UnitOfInformation.BYTES)

ALL_EDGE_OS_UNITS = [str(unit) for unit in list(UnitOfEdgeOS)]

SUPPORTED_REMOVED_ENTITIES_DEVICE_TYPES = [DeviceTypes.DEVICE, DeviceTypes.INTERFACE]

ENTITY_VALIDATIONS = {
    EntityValidation.MONITORED: lambda is_monitored, is_admin: is_monitored,
    EntityValidation.ADMIN_ONLY: lambda is_monitored, is_admin: is_admin,
    EntityValidation.NON_ADMIN_ONLY: lambda is_monitored, is_admin: not is_admin,
}
